name: Setup Elixir Env
description: Sets up Elixir, checks out code, and caches deps

inputs:
  should-download:
    required: true
    default: 'false'
    description: Should download build artifacts
  cache-name:
    required: true
    default: cache-elixir-deps
    description: Cache namespace

runs:
  using: 'composite'
  steps:
    - name: Read .tool-versions
      id: tool-versions
      run: |
        if [ -f .tool-versions ]; then
          echo "elixir-version=$(grep '^elixir ' .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
          echo "otp-version=$(grep '^erlang ' .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
        else
          echo "Error: .tool-versions file not found"
          exit 1
        fi
      shell: bash

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ steps.tool-versions.outputs.otp-version }}
        elixir-version: ${{ steps.tool-versions.outputs.elixir-version }}

    - name: Download build artifacts
      if: ${{ inputs.should-download == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    # Step: Define how to cache deps. Restores existing cache if present.
    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v4
      env:
        cache-name: cache-elixir-deps
      with:
        path: deps
        key:
          ${{ runner.os }}-mix-${{ inputs.cache-name }}-${{
          hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ inputs.cache-name }}-

    # Step: Define how to cache the `_build` directory. After the first run,
    # this speeds up tests runs a lot. This includes not re-compiling our
    # project's downloaded deps every run.
    - name: Cache _build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: _build
        key:
          ${{ runner.os }}-mix-${{ inputs.cache-name }}-${{
          hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ inputs.cache-name }}-

    # Step: Conditionally bust the cache when job is re-run.
    # Sometimes, we may have issues with incremental builds that are fixed by
    # doing a full recompile. In order to not waste dev time on such trivial
    # issues (while also reaping the time savings of incremental builds for
    # *most* day-to-day development), force a full recompile only on builds
    # that are retried.
    - name: Clean to rule out incremental build as a source of flakiness
      if: github.run_attempt != 1
      run: |
        mix deps.clean --all
        mix clean
      shell: sh