defmodule PilatesOnPhx.Repo.Migrations.AddStudiosDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:studios, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :address, :text, null: false
      add :timezone, :text, null: false, default: "America/New_York"
      add :max_capacity, :bigint, null: false, default: 50
      add :operating_hours, :map, null: false
      add :settings, :map, null: false, default: %{}
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "studios_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:studio_staff, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :permissions, {:array, :text}, null: false, default: []
      add :notes, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :studio_id,
          references(:studios,
            column: :id,
            name: "studio_staff_studio_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "studio_staff_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:studio_staff, [:studio_id, :user_id], unique: true)

    create table(:rooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :capacity, :bigint, null: false, default: 12
      add :settings, :map, null: false, default: %{}
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :studio_id,
          references(:studios,
            column: :id,
            name: "rooms_studio_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:equipment, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :equipment_type, :text, null: false
      add :serial_number, :text
      add :portable, :boolean, null: false, default: false
      add :maintenance_notes, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :studio_id,
          references(:studios,
            column: :id,
            name: "equipment_studio_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :room_id,
          references(:rooms,
            column: :id,
            name: "equipment_room_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:equipment, "equipment_studio_id_fkey")

    drop constraint(:equipment, "equipment_room_id_fkey")

    drop table(:equipment)

    drop constraint(:rooms, "rooms_studio_id_fkey")

    drop table(:rooms)

    drop constraint(:studio_staff, "studio_staff_studio_id_fkey")

    drop constraint(:studio_staff, "studio_staff_user_id_fkey")

    drop_if_exists index(:studio_staff, [:studio_id, :user_id])

    drop table(:studio_staff)

    drop constraint(:studios, "studios_organization_id_fkey")

    drop table(:studios)
  end
end
